{
 "title": "RaspberryPi4",
 "description": "Host rpi-4-2g",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memory used",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" }
     ]
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reads",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "mmcblk0" }
     ]
    },
    {
     "alias": "Writes",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "mmcblk0" }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1m",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" }
     ]
    },
    {
     "alias": "5m",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" }
     ]
    },
    {
     "alias": "15m",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rpi-4-2g" }
     ]
    }
   ]
  }
 ]
}